### ISSUE TITLE
Show method name when "Decode with ABI" is submitted

### ISSUE THREAD

**Issue by aviggiano** [swiss-knife-xyz/swiss-knife#28]
Hello,

First of all, thank you for building this great tool.

I'm using it to [decode `multicall` operations](https://calldata.swiss-knife.xyz/decoder?calldata=0xac9650d80000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000640cf8542f000000000000000000000000420000000000000000000000000000000000000600000000000000000000000000000000000000000000000000b1a2bc2ec5000000000000000000000000000087cdad83a779d785a729a91dbb9fe0db8be14b3b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c42e106f21000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000014d570bb2c28e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000244ccd8d4d1000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000967abc500000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000151800000000000000000000000000000000000000000000000000000000000278d000000000000000000000000000000000000000000000000000000000001da9c000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000470de4df82000000000000000000000000000000000000000000000000000000b1a2bc2ec50000000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000) on a smart contract, and although I have [submitted the ABI](https://gist.github.com/aviggiano/6fa7cb443439c94e577ef19cd0e22d61), it is failing to correctly decode each method name. It just shows `guessed_XXX`

When the ABI is present, I would expect it to also show the method name and input parameters

**Comment by apoorvlathey** [comment]
it's fixed now
<img width="736" alt="image" src="https://github.com/user-attachments/assets/6ec99b0b-119f-4f99-ab73-9e13bac84f79">
