### ISSUE TITLE
Connect wallet to query Storage Slots

### ISSUE THREAD

**Issue by johnson86tw** [swiss-knife-xyz/swiss-knife#31]
Hey, I want to query storage slot on base network but it's not on the menu. I think a better way to support multiple chain would be to allow users to connect their injected wallet and use the wallet provider to query data.

**Comment by apoorvlathey** [comment]
I am using wagmi, so it requires that all the networks that the user can connect their wallet to be defined before. I have updated the code so it uses almost all the chains.
