### ISSUE TITLE
Auto decode tx calldata

### ISSUE THREAD

**Issue by aviggiano** [swiss-knife-xyz/swiss-knife#32]
Building on top of this issue https://github.com/swiss-knife-xyz/swiss-knife/issues/28, I'd like to paste the tx hash or block explorer URL and automatically get the calldata

Steps to achieve this:
1. From tx, get ABI
2. From ABI, auto decode

**Comment by aviggiano** [comment]
This should also work for proxy contracts

**Comment by apoorvlathey** [comment]
It's already supported. You are referring to this right?
https://calldata.swiss-knife.xyz/decoder?tx=https://etherscan.io/tx/0xc4060f3a47774f7b1d092f4ace7426e7bd8348e1ba8c277be9b777fd757fdc38

**Comment by aviggiano** [comment]
Wow amazing
I didn't see it
Thanks
